spring:
  cache:
    type: redis
    cache-names: books
    redis:
      time-to-live: ${CACHE_TTL:30m}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/library_system}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        formal_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}
